// Build the dense resolved admin translation table
// src/admin/i18n.resolved.generated.ts.
//
// The admin twin of scripts/i18n_build.mjs. `en` (src/admin/i18n.en.ts) is the
// authoritative FLAT English base; the 13 non-English locales are FLAT overlays
// (src/admin/i18n.locales/<lang>.ts). Each overlay is merged onto a copy of `en`,
// with any omitted key filled from English, so every emitted locale is DENSE. The
// generated file types each locale ": AdminTranslations" (= typeof en), so tsc
// red-fails a missing or renamed key. The admin SPA reads this generated table,
// never the raw overlays (which may go sparse) - and it imports its OWN table, so
// the game locale data is never pulled into the admin bundle.
//
// Admin keys are already flat dotted strings, so there is no flatten/unflatten:
// the overlay IS the locale slice and merging is a shallow Object.assign.
//
// Zero runtime deps; bundles the TS source with esbuild (same pattern as
// scripts/i18n_build.mjs). Deterministic: key order is driven by `en`, no
// Date.now / Math.random - two runs on the same input are byte-identical
// (reproducibility-checked by tests/i18n_admin_catalog.test.ts).
//
// Usage:
//   node scripts/i18n_admin_build.mjs

import * as esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { pseudoLocalize } from './i18n_pseudo.mjs';

const root = process.cwd();
const OUT_PATH = path.join(root, 'src/admin/i18n.resolved.generated.ts');

// Authoritative ordered locale set (mirrors scripts/i18n_build.mjs LOCALES). `en`
// is the base; the rest are flat overlays. Drives emit order + supportedLanguages.
const LOCALES = [
  'en', 'es', 'es_ES', 'fr_FR', 'fr_CA', 'en_CA', 'it_IT', 'de_DE',
  'zh_CN', 'zh_TW', 'ko_KR', 'ja_JP', 'pt_BR', 'ru_RU',
];

// Dialect locales resolve through a base (base-resolution model): nested en -> base
// overlay -> dialect overlay. Mirror of scripts/i18n_build.mjs DIALECT_BASE.
const DIALECT_BASE = { es_ES: 'es', fr_CA: 'fr_FR', en_CA: 'en' };

function sourceModule(lang) {
  return lang === 'en' ? './src/admin/i18n.en' : `./src/admin/i18n.locales/${lang}`;
}

async function loadLocales() {
  const stub = LOCALES.map((lang) => `export { ${lang} } from '${sourceModule(lang)}';`).join('\n');
  const build = await esbuild.build({
    stdin: { contents: stub, resolveDir: root, sourcefile: 'admin-i18n-build-entry.ts', loader: 'ts' },
    bundle: true,
    platform: 'node',
    format: 'esm',
    write: false,
    logLevel: 'silent',
  });
  const dataUrl = `data:text/javascript;base64,${Buffer.from(build.outputFiles[0].text).toString('base64')}`;
  const mod = await import(dataUrl);
  const out = {};
  for (const lang of LOCALES) out[lang] = mod[lang];
  return out;
}

const isPresent = (v) => typeof v === 'string' && v.trim().length > 0;

function banner() {
  return [
    '// Generated by scripts/i18n_admin_build.mjs. Do not edit by hand.',
    '//',
    '// Dense resolved 14-locale ADMIN translation table: every locale overlaid onto',
    '// the authoritative flat `en` admin base, with any missing key filled from',
    "// English. Each locale is typed `: AdminTranslations` (= typeof en) so tsc",
    '// red-fails a missing or renamed key. The admin SPA consumes ONLY this file',
    '// (never the game locale table); regenerate with `npm run i18n:admin` (also',
    '// wired into `npm run build` and `pretest`). Reproducibility is checked by',
    '// tests/i18n_admin_catalog.test.ts.',
  ].join('\n');
}

function emit(resolved, pending, enXA) {
  const lines = [banner(), '', "import type { AdminTranslations } from './i18n.en';", ''];
  for (const lang of LOCALES) {
    lines.push(`export const ${lang}: AdminTranslations = ${JSON.stringify(resolved[lang], null, 2)};`);
    lines.push('');
  }
  lines.push('export const translations = {');
  for (const lang of LOCALES) lines.push(`  ${lang},`);
  lines.push('};');
  lines.push('');
  // Per-locale keys with NO real translation in the source overlay: the dense
  // table above carries the English FILL for each. The admin t() renders that
  // English on a non-release build and HARD-FAILS on a release build (the release
  // gate asserts this set is empty). Dialect-aware; `en` is the source, never
  // pending. Mirrors scripts/i18n_scan.mjs `providedByLang` so build + registry agree.
  lines.push('export const pending: Record<string, readonly string[]> = ' + JSON.stringify(pending, null, 2) + ';');
  lines.push('');
  // en_XA: the dev-only ADMIN pseudo-locale. Operators are users, so the
  // admin dashboard gets the same literal-surfacing tool as the game. Every admin
  // `en` value accent-pushed and bracketed with {placeholders} preserved. NOT a
  // member of `translations`, so it never enters the admin supportedLanguages, the
  // operator language list, or the admin release gate; the admin runtime loads it
  // only behind a dev gate (?lang=en_XA on a non-release build) and a production
  // build tree-shakes it out via an import.meta.env.PROD guard.
  lines.push(`export const en_XA: AdminTranslations = ${JSON.stringify(enXA, null, 2)};`);
  lines.push('');
  return lines.join('\n');
}

function computePending(enKeys, locales) {
  const pending = {};
  for (const lang of LOCALES) {
    if (lang === 'en') continue;
    const provided = new Set();
    const own = locales[lang] || {};
    for (const k of Object.keys(own)) if (isPresent(own[k])) provided.add(k);
    const base = DIALECT_BASE[lang];
    if (base === 'en') {
      for (const k of enKeys) provided.add(k); // English dialect inherits every key
    } else if (base) {
      const baseOverlay = locales[base] || {};
      for (const k of Object.keys(baseOverlay)) if (isPresent(baseOverlay[k])) provided.add(k);
    }
    pending[lang] = enKeys.filter((k) => !provided.has(k)).sort();
  }
  return pending;
}

async function main() {
  const locales = await loadLocales();
  const en = locales.en;
  const enKeys = Object.keys(en);
  const enKeySet = new Set(enKeys);

  // Fail loud on a phantom overlay key (one not in the English base). The flat
  // resolve below would otherwise smuggle it into the dense table and break the
  // `: AdminTranslations` excess-property contract. (Runtime backstop for the same
  // invariant tests/i18n_admin_catalog.test.ts asserts.)
  for (const lang of LOCALES) {
    if (lang === 'en') continue;
    for (const k of Object.keys(locales[lang] || {})) {
      if (!enKeySet.has(k)) {
        throw new Error(`i18n:admin: overlay "${lang}" has key "${k}" not present in the admin en base (typo/stale?)`);
      }
    }
  }

  const resolved = {};
  for (const lang of LOCALES) {
    const out = { ...en };
    if (lang !== 'en') {
      const baseLocale = DIALECT_BASE[lang];
      if (baseLocale && baseLocale !== 'en') Object.assign(out, locales[baseLocale]);
      Object.assign(out, locales[lang]);
    }
    resolved[lang] = out;
  }
  const pending = computePending(enKeys, locales);
  // Generate en_XA from the resolved (dense) admin `en` and emit it as a separate
  // dev-only export (never in `translations`).
  const enXA = pseudoLocalize(resolved.en);
  const text = emit(resolved, pending, enXA);
  writeFileSync(OUT_PATH, text);
  const pendingTotal = Object.values(pending).reduce((n, ks) => n + ks.length, 0);
  console.log(
    `generated ${path.relative(root, OUT_PATH)} (${LOCALES.length} locales + en_XA pseudo, ${enKeys.length} keys, ` +
      `pending=${pendingTotal}, ${Buffer.byteLength(text, 'utf8')} bytes)`,
  );
}

await main();
