// Build the dense resolved translation table src/ui/i18n.resolved.generated.ts.
//
// This is the load-bearing tsc safety net for the i18n scaling refactor. `en`
// (src/ui/i18n.en.ts) is the authoritative NESTED base; the 13 non-English
// locales are FLAT dotted-key overlays (`Record<string, string>`). Each
// overlay is unflattened back to a nested object and overlaid onto a deep copy of
// `en`, with any missing leaf filled from the English value, so every emitted
// locale is DENSE (no gaps). The generated file types each locale
// ": EnTranslations" (= typeof en), so tsc still red-fails any missing or renamed
// key. Client and admin read this generated table, never the raw per-locale
// overlays (which later become sparse).
//
// Zero runtime deps; bundles the TS source with esbuild (the same pattern as
// scripts/i18n_resolved_hash.mjs and scripts/export_loot_spreadsheet.mjs). Writes
// deterministically - key ordering is driven by `en`, indentation and quoting are
// fixed, and there are no timestamps / Date.now / Math.random anywhere - so two
// runs on the same input are byte-identical (reproducibility-checked like the
// media manifest).
//
// Usage:
//   node scripts/i18n_build.mjs   (re)generate src/ui/i18n.resolved.generated.ts

import * as esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { flatten, unflatten } from './i18n_flatten.mjs';
import { pseudoLocalize } from './i18n_pseudo.mjs';

const root = process.cwd();
const OUT_PATH = path.join(root, 'src/ui/i18n.resolved.generated.ts');

// The authoritative ordered locale set. `en` is the nested base; the other 13 are
// the flat dotted-key overlay files (src/ui/i18n.locales/<lang>.ts). This list
// drives both the emit order and the runtime supportedLanguages (Object.keys of
// the generated `translations`). The generator reads these SOURCE modules directly
// and never imports src/ui/i18n.ts, so it never depends on the file it generates
// (no circular import at build time).
const LOCALES = [
  'en',
  'es',
  'es_ES',
  'fr_FR',
  'fr_CA',
  'en_CA',
  'it_IT',
  'de_DE',
  'zh_CN',
  'zh_TW',
  'ko_KR',
  'ja_JP',
  'pt_BR',
  'ru_RU',
];

// Dialect locales declare a base locale. A dialect's (now
// divergence-only) overlay is applied ON TOP of its base locale's overlay, which
// is itself applied on top of nested `en`. So the resolve order for a dialect is
//   nested en -> base-locale overlay -> dialect overlay
// and any key the dialect omits falls through to the base, then to English. This
// is the single, data-driven declaration of the dialect graph; the resolver below
// reads it instead of branching on locale codes inline. A locale absent from this
// map has no base and is overlaid directly onto `en`, exactly as before.
const DIALECT_BASE = {
  es_ES: 'es',
  fr_CA: 'fr_FR',
  en_CA: 'en',
};

function sourceModule(lang) {
  return lang === 'en' ? './src/ui/i18n.en' : `./src/ui/i18n.locales/${lang}`;
}

// Bundle the source locale objects via a tiny stub and import the result. We pull
// `en` and each locale export by its code; none of this touches the generated file.
async function loadLocales() {
  const stub = LOCALES.map((lang) => `export { ${lang} } from '${sourceModule(lang)}';`).join('\n');
  const build = await esbuild.build({
    stdin: {
      contents: stub,
      resolveDir: root,
      sourcefile: 'i18n-build-entry.ts',
      loader: 'ts',
    },
    bundle: true,
    platform: 'node',
    format: 'esm',
    write: false,
    logLevel: 'silent',
  });
  const dataUrl = `data:text/javascript;base64,${Buffer.from(build.outputFiles[0].text).toString('base64')}`;
  const mod = await import(dataUrl);
  const out = {};
  for (const lang of LOCALES) out[lang] = mod[lang];
  return out;
}

function deepCopy(value) {
  return JSON.parse(JSON.stringify(value));
}

// Overlay `over` onto `base` (a fresh deep copy of en), in place: an object node
// recurses; any other leaf takes the overlay's value. Keys present only in `base`
// keep their English value (fill-from-English); keys present only in `over` are
// appended. Driving from a copy of `en` keeps the emitted key order stable.
function deepMerge(base, over) {
  for (const key of Object.keys(over)) {
    const overValue = over[key];
    const baseValue = base[key];
    const bothObjects =
      overValue && typeof overValue === 'object' && !Array.isArray(overValue) &&
      baseValue && typeof baseValue === 'object' && !Array.isArray(baseValue);
    if (bothObjects) {
      deepMerge(baseValue, overValue);
    } else {
      base[key] = overValue;
    }
  }
  return base;
}

function banner() {
  return [
    '// Generated by scripts/i18n_build.mjs. Do not edit by hand.',
    '//',
    '// Dense resolved 14-locale translation table: every locale overlaid onto the',
    '// authoritative nested `en`, with any missing leaf filled from English. Each',
    "// locale is typed `: EnTranslations` (= typeof en) so tsc red-fails a missing or",
    '// renamed key. The runtime, the client, and any table reader consume this file;',
    "// regenerate with `npm run i18n:build` (also wired into `npm run build` and",
    '// `pretest`). Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.',
  ].join('\n');
}

function emit(resolved, pending, enXA) {
  const lines = [banner(), '', "import type { EnTranslations } from './i18n.en';", ''];
  for (const lang of LOCALES) {
    lines.push(`export const ${lang}: EnTranslations = ${JSON.stringify(resolved[lang], null, 2)};`);
    lines.push('');
  }
  lines.push(`export const translations = {`);
  for (const lang of LOCALES) lines.push(`  ${lang},`);
  lines.push('};');
  lines.push('');
  // Per-locale dotted keys with NO real translation in the source overlay: the
  // dense table above carries the English FILL for each of them. t() renders that
  // English on a non-release build and HARD-FAILS on a release build (the release
  // gate asserts this set is empty, so the failure is a never-fires safety net).
  // Computed from the overlays, dialect-aware, mirroring scripts/i18n_scan.mjs's
  // `providedByLang`; `en` is the source and is never pending. EMPTY while the
  // overlays stay dense.
  lines.push('export const pending: Record<string, readonly string[]> = ' + JSON.stringify(pending, null, 2) + ';');
  lines.push('');
  // en_XA: the dev-only pseudo-locale. Every `en` leaf accent-pushed and
  // bracketed with {placeholders} preserved (see scripts/i18n_pseudo.mjs). It is
  // DELIBERATELY NOT a member of `translations` above, so it never enters
  // supportedLanguages, the language picker, hreflang, or the release gate. The
  // runtime loads it ONLY behind a dev gate (?lang=en_XA on a non-release build) to
  // surface hard-coded literals that never became t() keys, and a production build
  // tree-shakes it out via an import.meta.env.PROD guard. Typed `: EnTranslations`
  // because the transform preserves the `en` structure exactly.
  lines.push(`export const en_XA: EnTranslations = ${JSON.stringify(enXA, null, 2)};`);
  lines.push('');
  return lines.join('\n');
}

// A locale "provides" a key when its own overlay (or, for a dialect, its base
// chain) carries a non-empty value for it. The complement against `en`'s leaves is
// the per-locale `pending` set: untranslated keys the resolved table English-fills.
// This is the exact same rule as scripts/i18n_scan.mjs `providedByLang`, kept in
// lockstep so the build's runtime `pending` and the registry's `pending` agree.
const isPresent = (v) => typeof v === 'string' && v.trim().length > 0;

function computePending(en, locales) {
  const enFlatKeys = Object.keys(flatten(en));
  const pending = {};
  for (const lang of LOCALES) {
    if (lang === 'en') continue; // en is the authoritative source, never pending
    const provided = new Set();
    const own = locales[lang] || {};
    for (const k of Object.keys(own)) if (isPresent(own[k])) provided.add(k);
    const base = DIALECT_BASE[lang];
    if (base === 'en') {
      for (const k of enFlatKeys) provided.add(k); // English dialect inherits every leaf
    } else if (base) {
      const baseOverlay = locales[base] || {};
      for (const k of Object.keys(baseOverlay)) if (isPresent(baseOverlay[k])) provided.add(k);
    }
    pending[lang] = enFlatKeys.filter((k) => !provided.has(k)).sort();
  }
  return pending;
}

async function main() {
  const locales = await loadLocales();
  const en = locales.en;
  const resolved = {};
  for (const lang of LOCALES) {
    // `en` is nested and authoritative; every other locale is a flat dotted-key
    // overlay that we unflatten before overlaying onto a copy of `en`.
    // A dialect (DIALECT_BASE) additionally has its base locale's overlay applied
    // first, so its own overlay need only carry the keys that diverge from the base.
    const out = deepCopy(en);
    if (lang !== 'en') {
      const baseLocale = DIALECT_BASE[lang];
      // The base is `en` for en_CA (already the starting point, nothing to merge);
      // for es_ES/fr_CA it is another flat overlay applied before the dialect's.
      if (baseLocale && baseLocale !== 'en') {
        deepMerge(out, unflatten(locales[baseLocale]));
      }
      deepMerge(out, unflatten(locales[lang]));
    }
    resolved[lang] = out;
  }
  const pending = computePending(en, locales);
  // Generate en_XA from the resolved (dense) `en` so the pseudo table carries every
  // leaf, then emit it as a separate dev-only export (never in `translations`).
  const enXA = pseudoLocalize(resolved.en);
  const text = emit(resolved, pending, enXA);
  writeFileSync(OUT_PATH, text);
  console.log(
    `generated ${path.relative(root, OUT_PATH)} (${LOCALES.length} locales + en_XA pseudo, ${Buffer.byteLength(text, 'utf8')} bytes)`,
  );
}

await main();
