// The en_XA dev-only pseudo-locale.
//
// en_XA is generated by accent-pushing + bracketing every `en` leaf with
// {placeholders} preserved (scripts/i18n_pseudo.mjs). It is the one mechanism that
// catches hard-coded literals that never became t() keys: on screen, any text that
// stays plain ASCII with no brackets is an untranslated literal. These guards prove
// the generator output is correct AND that en_XA is excluded from every user-facing
// locale enumeration (supportedLanguages, the picker, hreflang, the release gate),
// while still being selectable via ?lang=en_XA on a NON-release build only.

import fs from "node:fs";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { en, en_XA } from "../src/ui/i18n.resolved.generated";
import { en as adminEn, en_XA as adminXA } from "../src/admin/i18n.resolved.generated";
import { supportedLanguages, isSupportedLanguage } from "../src/ui/i18n";
import { DICT as ADMIN_DICT } from "../src/admin/i18n";

const PLACEHOLDER = /\{[^}]*\}/g;
const ASCII_LETTER = /[A-Za-z]/;

// Walk two structurally-identical trees in parallel, collecting [path, enLeaf, xaLeaf].
function collectLeaves(
  enNode: unknown,
  xaNode: unknown,
  p: string,
  out: Array<[string, string, unknown]>,
): void {
  if (typeof enNode === "string") {
    out.push([p, enNode, xaNode]);
    return;
  }
  if (Array.isArray(enNode)) {
    enNode.forEach((v, i) => collectLeaves(v, (xaNode as unknown[] | undefined)?.[i], `${p}[${i}]`, out));
    return;
  }
  if (enNode && typeof enNode === "object") {
    for (const k of Object.keys(enNode)) {
      collectLeaves(
        (enNode as Record<string, unknown>)[k],
        (xaNode as Record<string, unknown> | undefined)?.[k],
        p ? `${p}.${k}` : k,
        out,
      );
    }
  }
}

describe("en_XA generator output (game)", () => {
  const leaves: Array<[string, string, unknown]> = [];
  collectLeaves(en, en_XA, "", leaves);

  it("transforms a non-trivial number of leaves", () => {
    expect(leaves.length).toBeGreaterThan(1000);
  });

  it("has the exact same leaf set as en (key parity, no missing/extra leaves)", () => {
    for (const [path, , xaLeaf] of leaves) {
      expect(typeof xaLeaf, `en_XA missing string leaf at ${path}`).toBe("string");
    }
  });

  it("brackets every leaf so an un-keyed literal is visually obvious", () => {
    for (const [path, , xaLeaf] of leaves) {
      const s = xaLeaf as string;
      expect(s.startsWith("["), `en_XA leaf not bracketed at ${path}: ${s}`).toBe(true);
      expect(s.endsWith("]"), `en_XA leaf not bracketed at ${path}: ${s}`).toBe(true);
    }
  });

  it("preserves every {placeholder} token EXACTLY", () => {
    for (const [path, enLeaf, xaLeaf] of leaves) {
      const enTokens = enLeaf.match(PLACEHOLDER) ?? [];
      const xaTokens = (xaLeaf as string).match(PLACEHOLDER) ?? [];
      expect(xaTokens, `placeholders changed at ${path}`).toEqual(enTokens);
    }
  });

  it("accent-pushes the literal text (no plain ASCII letters survive outside placeholders)", () => {
    for (const [path, enLeaf, xaLeaf] of leaves) {
      // Only leaves whose literal text (placeholders stripped) had ASCII letters can
      // be checked: a leaf of pure symbols/digits stays as-is inside the brackets.
      const enText = enLeaf.replace(PLACEHOLDER, "");
      if (!ASCII_LETTER.test(enText)) continue;
      const xaText = (xaLeaf as string).slice(1, -1).replace(PLACEHOLDER, "");
      expect(ASCII_LETTER.test(xaText), `un-accented ASCII letters at ${path}: ${xaLeaf}`).toBe(false);
    }
  });

  it("is deterministic and 1:1 (the same en leaf always yields the same en_XA leaf)", () => {
    // Two leaves with identical en text must have identical en_XA text.
    const map = new Map<string, string>();
    for (const [path, enLeaf, xaLeaf] of leaves) {
      const seen = map.get(enLeaf);
      if (seen === undefined) map.set(enLeaf, xaLeaf as string);
      else expect(xaLeaf, `non-deterministic transform at ${path}`).toBe(seen);
    }
  });
});

describe("en_XA generator output (admin)", () => {
  const leaves: Array<[string, string, unknown]> = [];
  collectLeaves(adminEn, adminXA, "", leaves);

  it("transforms the admin catalog with brackets + preserved placeholders", () => {
    expect(leaves.length).toBeGreaterThan(100);
    for (const [path, enLeaf, xaLeaf] of leaves) {
      const s = xaLeaf as string;
      expect(typeof s, `admin en_XA missing leaf at ${path}`).toBe("string");
      expect(s.startsWith("[") && s.endsWith("]"), `admin en_XA leaf not bracketed at ${path}`).toBe(true);
      expect((s.match(PLACEHOLDER) ?? []), `admin placeholders changed at ${path}`).toEqual(enLeaf.match(PLACEHOLDER) ?? []);
    }
  });
});

describe("en_XA is excluded from every user-facing locale enumeration", () => {
  it("is NOT a member of supportedLanguages (so never in the language picker)", () => {
    expect(supportedLanguages).not.toContain("en_XA");
  });

  it("is NOT a SupportedLanguage", () => {
    expect(isSupportedLanguage("en_XA")).toBe(false);
  });

  it("is NOT a key of the admin DICT (so never in the operator language list)", () => {
    expect(Object.keys(ADMIN_DICT)).not.toContain("en_XA");
  });

  it("is NOT referenced anywhere in index.html (no hreflang / picker SEO leak)", () => {
    // The static index.html carries both the hreflang <link> block and the player
    // language <select>; the pseudo-locale must appear in NEITHER. A whole-file,
    // case-insensitive check guards both at once and also catches the en-XA / EN_XA
    // spellings a future hand-edit might use. (The existing localization_coverage
    // hreflang test is presence-only and would not catch a leak.)
    const html = fs.readFileSync(path.resolve(process.cwd(), "index.html"), "utf8").toLowerCase();
    expect(html).not.toContain("en_xa");
    expect(html).not.toContain("en-xa");
  });
});

describe("?lang=en_XA dev selector (game runtime)", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
    vi.resetModules();
    delete process.env.I18N_RELEASE;
  });

  it("activates the pseudo-locale on a non-release build (bracketed/accented, base stays en, placeholders interpolate)", async () => {
    delete process.env.I18N_RELEASE;
    vi.resetModules();
    vi.stubGlobal("window", { location: { search: "?lang=en_XA" } });
    const mod = await import("../src/ui/i18n");

    // The base locale stays "en" and en_XA never enters supportedLanguages.
    expect(mod.getLanguage()).toBe("en");
    expect(mod.supportedLanguages).not.toContain("en_XA");

    const home = (mod.t as unknown as (k: string) => string)("nav.home");
    expect(home).toMatch(/^\[.*\]$/);
    expect(home).not.toBe("Home");

    // Placeholders still substitute under the pseudo-locale.
    const lc = (mod.t as unknown as (k: string, v?: Record<string, string | number>) => string)(
      "character.levelClass",
      { level: 7, className: "Maga" },
    );
    expect(lc).toContain("7");
    expect(lc).toContain("Maga");
  });

  it("is IGNORED on a release build, so no pseudo-locale can leak to production users", async () => {
    process.env.I18N_RELEASE = "1";
    vi.resetModules();
    vi.stubGlobal("window", { location: { search: "?lang=en_XA" } });
    const mod = await import("../src/ui/i18n");
    expect((mod.t as unknown as (k: string) => string)("nav.home")).toBe("Home");
  });
});
